# Site settings
title: Applied R Munich
header-img: img/home-bg.jpg
email: appliedrmunich@gmail.com
description: "Die R User Group in München"
baseurl: ""
url: "http://lmu-applied-r.github.io"
github_username:  lmu-applied-r
meetup_username: applied-r-munich


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
